import { ConvergeEvent } from "./types";

const AFI_RULES = [
  "Athletic events are conducted separately for boys and girls.",
  "Jumping the gun, whistle, or clapping results in a false start. Two false starts lead to disqualification.",
  "Runners must stay in their lane throughout the race.",
  "Athletic shoes or spikes are mandatory. Running barefoot is not permitted.",
  "Obstructing, jostling, or interfering with another runner's progress to gain an unfair advantage results in disqualification.",
  "Further rules follow the Athletic Federation of India (AFI). The referee's judgement is conclusive.",
];

export const EVENTS: ConvergeEvent[] = [
  // ---------------- SPORTS ----------------
  {
    slug: "100m-boys",
    name: "100 M",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Boy",
    genderNote: "Boys",
    about: "A 100 metre individual sprint event, conducted separately for boys and girls under Athletics Federation of India (AFI) regulations.",
    requirements: ["1 Boy participant per campus."],
    rules: AFI_RULES,
    whatYouNeed: ["Athletic shoes or spikes (mandatory)."],
  },
  {
    slug: "100m-girls",
    name: "100 M",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Girl",
    genderNote: "Girls",
    about: "A 100 metre individual sprint event, conducted separately for boys and girls under AFI regulations.",
    requirements: ["1 Girl participant per campus."],
    rules: AFI_RULES,
    whatYouNeed: ["Athletic shoes or spikes (mandatory)."],
  },
  {
    slug: "200m-boys",
    name: "200 M",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Boy",
    genderNote: "Boys",
    about: "A 200 metre individual sprint event, conducted separately for boys and girls under AFI regulations.",
    requirements: ["1 Boy participant per campus."],
    rules: AFI_RULES,
    whatYouNeed: ["Athletic shoes or spikes (mandatory)."],
  },
  {
    slug: "200m-girls",
    name: "200 M",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Girl",
    genderNote: "Girls",
    about: "A 200 metre individual sprint event, conducted separately for boys and girls under AFI regulations.",
    requirements: ["1 Girl participant per campus."],
    rules: AFI_RULES,
    whatYouNeed: ["Athletic shoes or spikes (mandatory)."],
  },
  {
    slug: "400m-boys",
    name: "400 M",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Boy",
    genderNote: "Boys",
    about: "A 400 metre individual sprint event, conducted separately for boys and girls under AFI regulations.",
    requirements: ["1 Boy participant per campus."],
    rules: AFI_RULES,
    whatYouNeed: ["Athletic shoes or spikes (mandatory)."],
  },
  {
    slug: "400m-girls",
    name: "400 M",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Girl",
    genderNote: "Girls",
    about: "A 400 metre individual sprint event, conducted separately for boys and girls under AFI regulations.",
    requirements: ["1 Girl participant per campus."],
    rules: AFI_RULES,
    whatYouNeed: ["Athletic shoes or spikes (mandatory)."],
  },
  {
    slug: "4x100m-relay",
    name: "4 x 100 M Relay",
    category: "sports",
    format: "Team",
    participantsLabel: "2 Boys + 2 Girls (4 total)",
    participantsCount: 4,
    genderNote: "Mixed",
    about: "A mixed relay of 2 boys and 2 girls per team, run under AFI regulations.",
    requirements: ["2 Boys and 2 Girls (4 participants in total)."],
    rules: [
      "Mixed boys and girls athletic event: 2 boys and 2 girls per team.",
      ...AFI_RULES,
    ],
    whatYouNeed: ["Athletic shoes or spikes (mandatory)."],
  },
  {
    slug: "shot-put-boys",
    name: "Shot Put",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Boy",
    genderNote: "Boys",
    about: "Individual shot put using a 7.26 kg shot, held separately for boys and girls.",
    requirements: ["1 Boy participant per campus."],
    rules: [
      "Criteria: 7.26 kg shot put.",
      "Separate competitions for boys and girls.",
      "Final score is the best of three non-consecutive throws.",
      "Stepping on the toe board or line is a foul.",
      "A legitimate put must be made with one hand, starting from the shoulder and nape of the neck. The shot must not drop below the shoulder.",
      "Further rules follow AFI. The referee's judgement is conclusive.",
    ],
  },
  {
    slug: "shot-put-girls",
    name: "Shot Put",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Girl",
    genderNote: "Girls",
    about: "Individual shot put using a 4 kg shot, held separately for boys and girls.",
    requirements: ["1 Girl participant per campus."],
    rules: [
      "Criteria: 4 kg shot put.",
      "Separate competitions for boys and girls.",
      "Final score is the best of three non-consecutive throws.",
      "Stepping on the toe board or line is a foul.",
      "A legitimate put must be made with one hand, starting from the shoulder and nape of the neck. The shot must not drop below the shoulder.",
      "Further rules follow AFI. The referee's judgement is conclusive.",
    ],
  },
  {
    slug: "discus-throw-boys",
    name: "Discus Throw",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Boy",
    genderNote: "Boys",
    about: "Individual discus throw using a 2 kg disc, held separately for boys and girls.",
    requirements: ["1 Boy participant per campus."],
    rules: [
      "Criteria: 2 kg disc.",
      "Final score is the best of three non-consecutive throws.",
      "Stepping on the toe board or crossing the line is a foul throw.",
      "The athlete may not touch the ground outside the designated circle during the throw.",
      "The athlete may not leave the circle before the discus lands; doing so is a foul.",
      "A throw landing outside the landing zone is void.",
      "Jumping the gun, whistling, or clapping causes a false start and may lead to elimination.",
      "Further rules follow AFI. The referee's judgement is conclusive.",
    ],
  },
  {
    slug: "discus-throw-girls",
    name: "Discus Throw",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Girl",
    genderNote: "Girls",
    about: "Individual discus throw using a 1.5 kg disc, held separately for boys and girls.",
    requirements: ["1 Girl participant per campus."],
    rules: [
      "Criteria: 1.5 kg disc.",
      "Final score is the best of three non-consecutive throws.",
      "Stepping on the toe board or crossing the line is a foul throw.",
      "The athlete may not touch the ground outside the designated circle during the throw.",
      "The athlete may not leave the circle before the discus lands; doing so is a foul.",
      "A throw landing outside the landing zone is void.",
      "Jumping the gun, whistling, or clapping causes a false start and may lead to elimination.",
      "Further rules follow AFI. The referee's judgement is conclusive.",
    ],
  },
  {
    slug: "high-jump-boys",
    name: "High Jump",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Boy",
    genderNote: "Boys",
    about: "Individual high jump, held separately for boys and girls under AFI regulations.",
    requirements: ["1 Boy participant per campus."],
    rules: [
      "Competitors must begin their approach from within the designated run-up area.",
      "Take-off must be from one foot only.",
      "Maximum of three attempts per height.",
      "Dislodging the crossbar or failing to clear it is a foul.",
      "Competitors may pass a height, but three consecutive failures result in elimination.",
      "The bar is raised progressively through the competition.",
      "Further rules follow AFI. The referee's decision is final and conclusive.",
    ],
  },
  {
    slug: "high-jump-girls",
    name: "High Jump",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Girl",
    genderNote: "Girls",
    about: "Individual high jump, held separately for boys and girls under AFI regulations.",
    requirements: ["1 Girl participant per campus."],
    rules: [
      "Competitors must begin their approach from within the designated run-up area.",
      "Take-off must be from one foot only.",
      "Maximum of three attempts per height.",
      "Dislodging the crossbar or failing to clear it is a foul.",
      "Competitors may pass a height, but three consecutive failures result in elimination.",
      "The bar is raised progressively through the competition.",
      "Further rules follow AFI. The referee's decision is final and conclusive.",
    ],
  },
  {
    slug: "basketball",
    name: "Basketball",
    category: "sports",
    format: "Team",
    participantsLabel: "3 Boys + 2 Girls",
    participantsCount: 5,
    substitutes: "2 Boys and 1 Girl",
    genderNote: "Mixed",
    about: "A mixed-team basketball tournament played in a knockout format.",
    requirements: ["3 Boys and 2 Girls (5 total).", "Substitutes: 2 Boys and 1 Girl."],
    rules: [
      "Four quarters of five minutes each (20 minutes total), order 5-1-5-2-5-1-5 with a 4-minute intermission.",
      "Knockout competition format.",
      "Each team gets two one-minute timeouts per game.",
      "A tie is settled with five additional minutes of extra time.",
      "All other rules follow FIBA (International Basketball Federation). The referee's decision is conclusive.",
    ],
  },
  {
    slug: "futsal",
    name: "Futsal",
    category: "sports",
    format: "Team",
    participantsLabel: "4 Boys + 2 Girls",
    participantsCount: 6,
    substitutes: "3 Boys and 1 Girl",
    genderNote: "Mixed",
    about: "A mixed-team futsal tournament following Futsal European Federation (FEF) rules.",
    requirements: ["4 Boys and 2 Girls (6 total).", "Substitutes: 3 Boys and 1 Girl."],
    rules: [
      "Each match is 20 minutes (two 10-minute halves) with a 5-minute break at half-time.",
      "One 1-minute timeout per half; none in extra time.",
      "Substitutions may be made at any time, in the designated substitution zones only.",
      "Penalty shoot-outs are taken from the centre of the D, two steps before the ball's position.",
      "Goalkeepers have five seconds to release the ball and may roam anywhere on the pitch.",
      "No offside; goals cannot be scored directly from kick-off.",
      "All other rules follow the Futsal European Federation (FEF). The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Football spikes/boots (mandatory).", "Stockings, shin guards and other safety gear (recommended)."],
  },
  {
    slug: "volleyball",
    name: "Volleyball",
    category: "sports",
    format: "Team",
    participantsLabel: "4 Boys + 2 Girls",
    participantsCount: 6,
    substitutes: "3 Boys and 1 Girl",
    genderNote: "Mixed",
    about: "A mixed-team volleyball tournament following FIVB rules.",
    requirements: ["4 Boys and 2 Girls (6 total).", "Substitutes: 3 Boys and 1 Girl."],
    rules: [
      "6 players per squad on court.",
      "Matches are best of 3 sets, 15 rally points per set (25 points in semi-finals and finals).",
      "Two one-minute timeouts per team per game.",
      "LIBERO is allowed.",
      "In a deuce, play continues to a 2-point lead up to 17/27 points.",
      "All other rules follow FIVB (Fédération Internationale de Volleyball). The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Non-marking shoes (compulsory)."],
  },
  {
    slug: "table-tennis-boys",
    name: "Table Tennis",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Boy",
    genderNote: "Boys",
    about: "Singles table tennis, held separately for boys and girls under ITTF rules.",
    requirements: ["1 Boy participant per campus."],
    rules: [
      "Matches are best of 3 sets of 11 points; semi-finals/finals are best of 5 sets of 11 points.",
      "Deuce in the deciding set requires a 2-point lead to win.",
      "The ball must rest on an open palm and be tossed at least 6 inches before serving.",
      "A legal serve that touches the net must be re-served.",
      "Further rules follow ITTF (International Table Tennis Federation). The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Own table tennis bat (balls provided)."],
  },
  {
    slug: "table-tennis-girls",
    name: "Table Tennis",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Girl",
    genderNote: "Girls",
    about: "Singles table tennis, held separately for boys and girls under ITTF rules.",
    requirements: ["1 Girl participant per campus."],
    rules: [
      "Matches are best of 3 sets of 11 points; semi-finals/finals are best of 5 sets of 11 points.",
      "Deuce in the deciding set requires a 2-point lead to win.",
      "The ball must rest on an open palm and be tossed at least 6 inches before serving.",
      "A legal serve that touches the net must be re-served.",
      "Further rules follow ITTF (International Table Tennis Federation). The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Own table tennis bat (balls provided)."],
  },
  {
    slug: "table-tennis-doubles",
    name: "Table Tennis Doubles",
    category: "sports",
    format: "Team",
    participantsLabel: "1 Boy + 1 Girl",
    participantsCount: 2,
    genderNote: "Mixed",
    about: "Mixed doubles table tennis under ITTF rules.",
    requirements: ["1 Boy and 1 Girl per team."],
    rules: [
      "Matches are best of 3 sets of 11 points; semi-finals/finals are best of 5 sets of 11 points.",
      "Deuce in the deciding set requires a 2-point lead to win.",
      "Further rules follow ITTF (International Table Tennis Federation). The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Own table tennis bats (balls provided)."],
  },
  {
    slug: "throwball",
    name: "Throwball",
    category: "sports",
    format: "Team",
    participantsLabel: "7 Girls",
    participantsCount: 7,
    substitutes: "4 Girls",
    genderNote: "Girls",
    about: "A girls' team throwball tournament under International Throwball Federation rules.",
    requirements: ["7 Girls per team.", "Substitutes: 4 Girls."],
    rules: [
      "Matches are best of 3 sets to 15 points, with one 2-minute timeout per team per match.",
      "In a deuce, play continues to a 2-point lead up to 17 points.",
      "Service is given from behind the backline (corners only) within five seconds of the whistle.",
      "Double touches are not allowed when receiving the service.",
      "A player may hold the ball for a maximum of 3 seconds; the same player serves until service breaks.",
      "Further rules follow the ITF (International Throwball Federation). The referee's judgement is conclusive.",
    ],
  },
  {
    slug: "badminton-boys",
    name: "Badminton",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Boy",
    genderNote: "Boys",
    about: "Singles badminton, held separately for boys and girls under WBF rules.",
    requirements: ["1 Boy participant per campus."],
    rules: [
      "Each match consists of 3 sets of 15 points; semi-finals/finals are best of three sets of 21 rally points.",
      "In a deuce, play extends up to 30 with 21 as a golden point.",
      "2-minute break after each set.",
      "Server and receiver must stand within their service courts, both feet stationary, until the shuttle is struck.",
      "Further rules follow the WBF (World Badminton Federation). The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Own racquet (shuttlecocks provided).", "Non-marking shoes (compulsory)."],
  },
  {
    slug: "badminton-girls",
    name: "Badminton",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Girl",
    genderNote: "Girls",
    about: "Singles badminton, held separately for boys and girls under WBF rules.",
    requirements: ["1 Girl participant per campus."],
    rules: [
      "Each match consists of 3 sets of 15 points; semi-finals/finals are best of three sets of 21 rally points.",
      "In a deuce, play extends up to 30 with 21 as a golden point.",
      "2-minute break after each set.",
      "Server and receiver must stand within their service courts, both feet stationary, until the shuttle is struck.",
      "Further rules follow the WBF (World Badminton Federation). The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Own racquet (shuttlecocks provided).", "Non-marking shoes (compulsory)."],
  },
  {
    slug: "badminton-doubles",
    name: "Badminton Doubles",
    category: "sports",
    format: "Team",
    participantsLabel: "1 Boy + 1 Girl",
    participantsCount: 2,
    genderNote: "Mixed",
    about: "Mixed doubles badminton under WBF rules.",
    requirements: ["1 Boy and 1 Girl per team."],
    rules: [
      "Each match consists of 3 sets of 15 points; semi-finals/finals are best of three sets of 21 rally points.",
      "In a deuce, play extends up to 30 with 21 as a golden point.",
      "Further rules follow the WBF (World Badminton Federation). The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Own racquets (shuttlecocks provided).", "Non-marking shoes (compulsory)."],
  },
  {
    slug: "carrom",
    name: "Carrom",
    category: "sports",
    format: "Open",
    participantsLabel: "Open (1 participant per campus)",
    genderNote: "Open",
    about: "An open individual carrom event under International Carrom Federation rules.",
    requirements: ["1 participant per campus (open category)."],
    rules: [
      "The player scoring the maximum points wins the round.",
      "Thumbing or backstroke is not allowed.",
      "Red coins are worth 3 points; black/white coins are worth 1 point.",
      "A minus stroke is penalised by 1 coin.",
      "A striker or carrom man leaving the board is a foul.",
      "The player who breaks plays white.",
      "Touching the opponent's coin before your own is penalised by 1 coin.",
      "All other rules follow the ICF (International Carrom Federation). The referee's judgement is conclusive.",
    ],
  },
  {
    slug: "chess",
    name: "Chess",
    category: "sports",
    format: "Open",
    participantsLabel: "Open (1 participant per campus)",
    genderNote: "Open",
    about: "An open individual chess event under FIDE rules with rapid time controls.",
    requirements: ["1 participant per campus (open category)."],
    timeLimit: "20 minutes per game (10 minutes per player).",
    rules: [
      "Maximum of 20 minutes per game (10 minutes per player).",
      "The host provides the chess clock, board, and pieces.",
      "30 seconds are allowed between moves.",
      "A maximum of 3 illegal moves is allowed before disqualification.",
      "50 moves are allowed if the king is the last piece left on the board.",
      "A draw is settled by piece count.",
      "Touch-and-move rules apply.",
      "All other rules follow FIDE (World Chess Federation). The referee's judgement is conclusive.",
    ],
  },
  {
    slug: "powerlifting-boys",
    name: "Powerlifting",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 participant per weight category",
    genderNote: "Boys",
    about: "Boys' powerlifting contested in three weight categories: up to 60 kg, up to 70 kg, and up to 80 kg.",
    requirements: [
      "Weight categories: up to 60 kg / up to 70 kg / up to 80 kg.",
      "1 participant per category, maximum 3 participants per campus, each in only one category.",
    ],
    rules: [
      "Two rounds: bench press and deadlift.",
      "Bench press: shoulders and buttocks must stay in contact with the bench; toes in solid contact with the platform (blocks permitted).",
      "Deadlift: the bar must not travel downward before the final position; lifter must stand erect with shoulders back and knees locked at the top; the bar may not rest on the thighs, and no stepping forward, backward or laterally during the lift's up phase; the bar must be lowered under control with both hands.",
      "The winner is the participant who lifts the heaviest weight.",
      "All other rules follow the International Powerlifting Federation (IPF). The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Own safety equipment (wristband, belt, etc.)."],
  },
  {
    slug: "bgmi",
    name: "Battlegrounds Mobile India (BGMI)",
    category: "sports",
    format: "Open",
    participantsLabel: "Open (4 participants per campus)",
    participantsCount: 4,
    substitutes: "2",
    genderNote: "Open",
    about: "An esports squad tournament of 3 classic BGMI matches, played on a single shared device per team.",
    requirements: ["4 participants per campus (squad).", "Substitutes: 2 (optional)."],
    rules: [
      "The tournament comprises 3 classic matches.",
      "Only one iPad per team is allowed.",
      "Cheating or hacking results in disqualification.",
      "Unsportsmanlike conduct results in penalties and point deductions.",
      "Matches are scheduled in advance; punctuality is mandatory.",
      "Substitutions are allowed between matches only.",
      "All other rules follow the rulebook issued by Krafton India Battlegrounds. The referee's judgement is conclusive.",
    ],
    important: ["Scoring: 1 point per kill, 15 points for a chicken dinner."],
  },
  {
    slug: "lawn-tennis",
    name: "Lawn Tennis",
    category: "sports",
    format: "Team",
    participantsLabel: "1 Boy + 1 Girl",
    participantsCount: 2,
    genderNote: "Mixed",
    about: "Mixed doubles lawn tennis under ITF regulations.",
    requirements: ["1 Boy and 1 Girl per team."],
    rules: [
      "Matches are best of 3 sets of 6 games, with a tiebreak at 6-6.",
      "In a tiebreak, the first team to 7 points with a 2-point lead wins the set.",
      "1-minute break between sets.",
      "The server must serve from behind the baseline, within the service box.",
      "Two consecutive faults in a point is a double fault, awarding the point to the opponent.",
      "Further rules follow ITF (International Tennis Federation). The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Own racquets (balls provided)."],
  },
  {
    slug: "squash-boys",
    name: "Squash",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Boy",
    genderNote: "Boys",
    about: "Singles squash, held separately for boys and girls under World Squash Federation rules.",
    requirements: ["1 Boy participant per campus."],
    rules: [
      "Matches are best of 3 sets of 11 points, with a tiebreak at 10-10 requiring a 2-clear-point win.",
      "The ball must be hit within the boundaries and eventually strike the back wall.",
      "A let is called for accidental interference; a foul is called for deliberate interference.",
      "The ball cannot be hit twice or carried.",
      "One foot must stay in the service box when serving; the same applies to the returner.",
      "Returns may be taken on the volley or after the bounce.",
      "Further rules follow the World Squash Federation Ltd. The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Own racquet.", "Non-marking shoes (compulsory)."],
  },
  {
    slug: "squash-girls",
    name: "Squash",
    category: "sports",
    format: "Individual",
    participantsLabel: "1 Girl",
    genderNote: "Girls",
    about: "Singles squash, held separately for boys and girls under World Squash Federation rules.",
    requirements: ["1 Girl participant per campus."],
    rules: [
      "Matches are best of 3 sets of 11 points, with a tiebreak at 10-10 requiring a 2-clear-point win.",
      "The ball must be hit within the boundaries and eventually strike the back wall.",
      "A let is called for accidental interference; a foul is called for deliberate interference.",
      "The ball cannot be hit twice or carried.",
      "One foot must stay in the service box when serving; the same applies to the returner.",
      "Returns may be taken on the volley or after the bounce.",
      "Further rules follow the World Squash Federation Ltd. The referee's judgement is conclusive.",
    ],
    whatYouNeed: ["Own racquet.", "Non-marking shoes (compulsory)."],
  },

  // ---------------- CULTURAL ----------------
  {
    slug: "campus-parade",
    name: "Opening Ceremony — Campus Parade",
    category: "cultural",
    format: "Group",
    participantsLabel: "50 (full contingent)",
    participantsCount: 50,
    nonCompetitive: true,
    about: "The full campus contingent marches in the Converge opening ceremony parade, led by a captain carrying the campus flag.",
    requirements: ["All 50 registered participants of the campus contingent."],
    rules: [
      "Participant registration time: 60 minutes prior to the event.",
      "All participating students must be part of the parade during the opening ceremony.",
      "All students are required to wear Converge tracksuits.",
      "Each campus team performs in rows of 3, led by a captain carrying the campus flag.",
    ],
    important: ["This event is non-competitive and carries no points."],
  },
  {
    slug: "ms-mr-converge",
    name: "Ms. & Mr. Converge",
    category: "cultural",
    format: "Duet",
    participantsLabel: "1 Girl + 1 Boy",
    participantsCount: 2,
    theme: "Prism of Persona (Vibrancy & Charm)",
    timeLimit: "2 minutes (Round 1) + 90 seconds (ramp walk)",
    about: "A personality pageant celebrating the colourful, maximalist spirit of Indian art, rewarding versatility, bold personalities and creative edge.",
    requirements: ["1 Girl and 1 Boy per campus."],
    rules: [
      "Participant registration time: 60 minutes prior to the event.",
      "Round 1: Couple Talent Show.",
      "Round 2: Ramp Walk and Q&A.",
      "Time limit: 2 minutes for Round 1 and 90 seconds for the ramp walk; exceeding the limit leads to a marks deduction.",
      "The performance must involve both participants.",
      "Music must be submitted in MP3 format at registration to avoid technical glitches.",
      "Both participants must answer questions individually or together, as directed by the jury.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["Performance music in MP3 format, submitted at registration."],
    evaluationCriteria: ["Relevance to theme", "Creativity & talent", "Confidence & walk", "Overall impact"],
  },
  {
    slug: "solo-singing",
    name: "Solo Singing",
    category: "cultural",
    format: "Individual",
    participantsLabel: "1 participant",
    participantsCount: 1,
    theme: "Echoes of Gold (Vocal Powerhouse)",
    timeLimit: "2 minutes stage set-up + 3 minutes performance",
    about: "A tribute to the Indian Idol format — performers bring big, dramatic, maximalist vocal arrangements to the stage.",
    requirements: ["1 participant per campus."],
    rules: [
      "Participant registration time: 60 minutes prior to the event.",
      "Time limit: 2 minutes of stage set-up + 3 minutes of performance; exceeding the limit leads to a marks deduction.",
      "Performers may be accompanied by ONE instrumentalist or a karaoke track.",
      "Music must be submitted in MP3 format at registration to avoid technical glitches.",
      "Deviation from the theme leads to disqualification.",
      "Participants must be well dressed and in keeping with the theme.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["Performance music in MP3 format, submitted at registration."],
    evaluationCriteria: ["Choice of song", "Voice quality", "Control & pronunciation", "Authenticity & cultural representation", "Overall impact"],
  },
  {
    slug: "duet-singing",
    name: "Duet Singing",
    category: "cultural",
    format: "Duet",
    participantsLabel: "2 participants",
    participantsCount: 2,
    theme: "Harmonix: Duel of Duality (Contrast & Chemistry)",
    timeLimit: "2 minutes stage set-up + 4 minutes performance",
    about: "A vocal battle and blend between two distinct vocal tones.",
    requirements: ["2 participants per campus."],
    rules: [
      "Participant registration time: 60 minutes prior to the event.",
      "Time limit: 2 minutes of stage set-up + 4 minutes of performance; exceeding the limit leads to a marks deduction.",
      "Performers may be accompanied by ONE instrumentalist or a karaoke track.",
      "Music must be submitted in MP3 format at registration to avoid technical glitches.",
      "Deviation from the theme leads to disqualification.",
      "Participants must be well dressed and in keeping with the theme.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["Performance music in MP3 format, submitted at registration."],
    evaluationCriteria: ["Choice of song", "Voice quality, control & pronunciation", "Authenticity & cultural representation", "Overall impact"],
  },
  {
    slug: "solo-dance",
    name: "Solo Dance",
    category: "cultural",
    format: "Individual",
    participantsLabel: "1 participant",
    participantsCount: 1,
    theme: "Navarasa Unbound",
    timeLimit: "2 minutes stage set-up + 3 minutes performance",
    about: "A drama-led solo centred on Abhinaya and emotional shifts, navigating contrasting emotions.",
    requirements: ["1 participant per campus."],
    rules: [
      "Participant registration time: 60 minutes prior to the event.",
      "Time limit: 3 minutes of performance; exceeding the limit leads to a marks deduction.",
      "Performance/choreography must be based on the given theme.",
      "Music must be submitted in MP3 format at registration to avoid technical glitches.",
      "No flammables may be used.",
      "No property will be provided by the host.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["Performance music in MP3 format, submitted at registration."],
    evaluationCriteria: ["Relevance to theme", "Use of stage space", "Steps & expressions", "Costume", "Overall impact"],
  },
  {
    slug: "duet-dance",
    name: "Duet Dance",
    category: "cultural",
    format: "Duet",
    participantsLabel: "2 participants",
    participantsCount: 2,
    theme: "Viraha & Milan: The Royal Court Duet (Semi-Classical / Bollywood Contemporary)",
    timeLimit: "2 minutes stage set-up + 4 minutes performance",
    about: "A story-driven duet depicting royal romance, longing and reunion, inspired by classic Indian poetry.",
    requirements: ["2 participants per campus."],
    rules: [
      "Participant registration time: 60 minutes prior to the event.",
      "Time limit: 3 minutes of performance; exceeding the limit leads to a marks deduction.",
      "Performance/choreography must be based on the given theme.",
      "Music must be submitted in MP3 format at registration to avoid technical glitches.",
      "No flammables may be used.",
      "No property will be provided by the host.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["Performance music in MP3 format, submitted at registration."],
    evaluationCriteria: ["Relevance to theme", "Use of stage space", "Steps & expressions", "Costume", "Overall impact"],
  },
  {
    slug: "group-dance",
    name: "Group Dance",
    category: "cultural",
    format: "Group",
    participantsLabel: "10 participants",
    participantsCount: 10,
    theme: "Leela-Regalia — The Procession of Kings",
    timeLimit: "2 minutes stage set-up + 5 minutes performance",
    about: "A massive celebration resembling a royal Indian procession — choreography should represent the historical pride of the country.",
    requirements: ["10 participants per campus."],
    rules: [
      "Participant registration time: 60 minutes prior to the event.",
      "Time limit: 2 minutes of stage set-up + 5 minutes of performance; exceeding the limit leads to a marks deduction.",
      "Performance/choreography must be based on the given theme.",
      "Use of one prop is mandatory.",
      "Content with hate against individuals or religion, any dual meaning, or obscene content is strictly prohibited and leads to disqualification.",
      "Music must be submitted in MP3 format at registration to avoid technical glitches.",
      "No flammables may be used.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["Performance music in MP3 format, submitted at registration.", "At least one prop (mandatory)."],
    evaluationCriteria: ["Relevance to theme", "Use of props & stage space", "Steps & expressions", "Costume & makeup", "Coordination & choreography", "Overall impact"],
  },
  {
    slug: "battle-of-bands",
    name: "Battle of Bands",
    category: "cultural",
    format: "Group",
    participantsLabel: "6 participants",
    participantsCount: 6,
    theme: "Sonic Overload",
    timeLimit: "10 minutes stage set-up + 8 minutes performance",
    about: "A maximalist band showdown with complex arrangements, fast tempo switches, dramatic crowd engagement and wall-of-sound instrumentals.",
    requirements: ["6 participants per campus."],
    rules: [
      "Participant registration time: 60 minutes prior to the event.",
      "Time limit: 8 minutes performance + 10 minutes set-up; exceeding the limit leads to a marks deduction.",
      "A minimum of 2 instrumentalists and 1 lead vocalist is compulsory.",
      "Students bring their own instruments; drums and a keyboard are provided by the host.",
      "Content with hate against individuals or religion, any dual meaning, or obscene content is strictly prohibited and leads to disqualification.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["Own instruments (drums and keyboard provided by host)."],
    evaluationCriteria: ["Music idea", "Stage presence", "Relevance to theme", "Audience engagement", "Synchronization"],
  },
  {
    slug: "design-showcase-competition",
    name: "Design Showcase Competition",
    category: "cultural",
    format: "Group",
    participantsLabel: "Up to 3 (Designer, optional Stylist, mandatory Model)",
    participantsCount: 3,
    theme: "Rang Regalia (Avant-Garde Ensemble)",
    timeLimit: "Ramp presentation: maximum 3 minutes",
    about: "Teams conceptualise and create an Avant-Garde Ensemble inspired by the CONVERGE 2026 theme, encouraging innovation, sustainability, experimentation and creative expression through unconventional materials.",
    requirements: [
      "A team may have up to 3 students: Designer(s), optional Stylist/Creative Support, and a mandatory Model.",
    ],
    rules: [
      "The final ensemble must comprise a minimum 50% unconventional/non-textile materials and a maximum 50% textile-based materials.",
      "Sustainable and recycled materials are encouraged.",
      "Each team must submit: a concept note (max 300 words), a mood board, a design illustration/sketch, a material board indicating percentage and type of materials used, and a brief theme-interpretation note — submitted as a printed document.",
      "Teams present their completed ensemble on the ramp during Converge; maximum ramp presentation duration is 3 minutes.",
      "The ensemble must be original work created specifically for CONVERGE 2026; previously exhibited, published, or award-winning works are not permitted.",
      "Teams must ensure the safety and comfort of the model; hazardous materials and unsafe constructions are strictly prohibited.",
      "The organising committee may disqualify entries violating competition guidelines and may photograph/record entries for educational, promotional and archival purposes.",
      "Any dispute on rule interpretation is resolved by the organising committee, whose decision is final.",
    ],
    whatYouNeed: [
      "Printed submission: concept note, mood board, design illustration/sketch, material board.",
      "Completed ensemble for the ramp presentation.",
    ],
    evaluationCriteria: ["Theme interpretation", "Innovation & creativity", "Use of unconventional materials", "Craftsmanship & construction", "Visual impact & styling", "Presentation"],
  },

  // ---------------- ESSE ----------------
  {
    slug: "nukkad-natak",
    name: "Nukkad Natak (Street Play)",
    category: "esse",
    format: "Group",
    participantsLabel: "10 participants",
    participantsCount: 10,
    theme: "Reel India vs Real India",
    timeLimit: "2 minutes stage set-up + 10 minutes performance",
    about: "A street-theatre performance built on the given theme, staged for a live audience.",
    requirements: ["10 participants per campus."],
    rules: [
      "Registration begins 60 minutes prior to the event.",
      "Each team gets 2 minutes for stage set-up and 10 minutes for performance; a warning bell rings after 8 minutes. Exceeding the time limit can lead to disqualification.",
      "The team must work within the given theme.",
      "Performances must be appropriate and in line with social norms; content violations lead to disqualification.",
      "Use of abusive or offensive language is prohibited.",
      "Use of mics and speakerphones is not allowed.",
      "Judges may stop any act that violates the rules or general decency.",
      "The jury's decision is final.",
    ],
    important: ["All props and costumes must be carried by the teams; nothing is provided by the host campus."],
    evaluationCriteria: ["Relatability and connection to the audience / overall impact", "Relevance of the theme", "Originality", "Props and their usage", "Time limit"],
  },
  {
    slug: "monologue",
    name: "Monologue",
    category: "esse",
    format: "Individual",
    participantsLabel: "1 participant",
    participantsCount: 1,
    theme: "The Last Artist (a quiet world where imperfect hands are slowly becoming a forgotten language)",
    timeLimit: "5 minutes",
    about: "A single-round solo spoken-word performance built entirely around the given theme, without the use of props.",
    requirements: ["1 participant per campus."],
    rules: [
      "Registration begins 60 minutes prior to the event.",
      "Each participant gets 5 minutes for performance; a warning bell rings after 4 minutes. Exceeding the time limit can lead to disqualification.",
      "Use of props is prohibited.",
      "The event consists of 1 round.",
      "Judges may stop any act that violates the rules or general decency.",
      "No participant may point out any individual or religion in any way; double-meaning or obscene content is strictly prohibited and leads to disqualification.",
      "The jury's decision is final.",
    ],
    important: ["No props allowed."],
    evaluationCriteria: ["Relevance of content", "Dialogues & expressions", "Audience interaction", "Content quality", "Body language"],
  },
  {
    slug: "face-painting",
    name: "Face Painting",
    category: "esse",
    format: "Team",
    participantsLabel: "2 participants (1 Artist + 1 Model)",
    participantsCount: 2,
    theme: "Provided at the time of registration",
    timeLimit: "90 minutes (including 5 minutes for concept explanation)",
    about: "A live face-art event where an artist paints a model's face around a theme revealed at registration.",
    requirements: ["1 Artist and 1 Model per campus."],
    rules: [
      "Registration begins 60 minutes prior to the event.",
      "The idea must be original and inspired by the provided theme.",
      "The 90-minute time limit includes 5 minutes for concept explanation.",
      "Using a picture reference from the internet or print media is not allowed.",
      "The participant must bring their own paint, brushes, and makeup; nothing is provided by the host campus.",
      "The artist is responsible for hygiene and ensuring no harm is caused to the model.",
      "The award is given only to the artist.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["Own paint, brushes and makeup (nothing provided by host)."],
    evaluationCriteria: ["Creativity", "Utilisation of the face as a canvas", "Technique and precision", "Time adherence"],
  },
  {
    slug: "stand-up-comedy",
    name: "Stand-Up Comedy",
    category: "esse",
    format: "Individual",
    participantsLabel: "1 participant",
    participantsCount: 1,
    theme: "Provided at the time of registration",
    timeLimit: "6 minutes",
    about: "A solo stand-up comedy set performed on a theme revealed at registration.",
    requirements: ["1 participant per campus."],
    rules: [
      "Registration begins 60 minutes prior to the event.",
      "Each participant gets 6 minutes for performance; a warning bell rings after 5 minutes. Exceeding the time limit can lead to disqualification.",
      "No props allowed.",
      "The script, including jokes and routine, must be self-written.",
      "Content must not be offensive to any religion or person; double-meaning or obscene content is strictly prohibited.",
      "Participants must strictly adhere to the time limit.",
      "Judges may stop any act that violates the rules or general conduct.",
      "The jury's decision is final.",
    ],
    important: ["No props allowed."],
    evaluationCriteria: ["Relevance of content", "Dialogues & expressions", "Audience interaction", "Content quality", "Body language"],
  },

  // ---------------- LITERARY ----------------
  {
    slug: "brush-battle",
    name: "Brush Battle",
    category: "literary",
    format: "Team",
    participantsLabel: "2 participants",
    participantsCount: 2,
    theme: "On spot",
    timeLimit: "180 minutes total (ideation + execution)",
    about: "A live-painting competition where teams ideate and execute a 2D artwork on an on-the-spot theme.",
    requirements: ["2 participants per campus."],
    rules: [
      "Registration begins 60 minutes before the event.",
      "Participants must report 20 minutes before the scheduled start.",
      "Total time allotted is 180 minutes, including ideation and execution.",
      "Concept development must be completed on paper and submitted to the jury within the first 30 minutes.",
      "The host provides only the canvas, sized 3 ft × 4 ft. Only 2D artworks are accepted.",
      "Participants must bring all other materials required to create their artwork.",
      "Judges may disqualify any artwork deemed offensive, inappropriate, or unsuitable.",
      "Cheating, plagiarism, mobile phone use, or copying another participant's work results in immediate disqualification. Adding to the artwork after submitting the concept note results in a mark deduction.",
      "Completed canvases are submitted to the Literary Club of the host campus after evaluation.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["All painting materials except the canvas (canvas, 3 ft × 4 ft, provided by host)."],
    evaluationCriteria: ["Creativity & originality", "Relevance to the theme", "Understanding of art & design elements", "Visual impact", "Cleanliness & finish"],
  },
  {
    slug: "mime",
    name: "Mime",
    category: "literary",
    format: "Group",
    participantsLabel: "5 participants",
    participantsCount: 5,
    theme: "Announced at the time of registration",
    timeLimit: "4 minutes",
    about: "A silent, expression-led group performance set to music and Foley sound effects.",
    requirements: ["5 participants per campus."],
    rules: [
      "Registration begins 24 hours before the event.",
      "Audio tracks in MP3 format must be submitted 60 minutes before the event (max 10 MB).",
      "Performance time limit is 4 minutes; a warning bell rings at 3 minutes.",
      "No props are allowed during the performance.",
      "Prescribed mime attire: black pants, black T-shirt, white hand gloves or painted hands, and white face paint.",
      "Non-submission of the audio file within the stipulated 60 minutes results in cancellation of participation.",
      "The act must not contain offensive, abusive, or unparliamentary content in any form.",
      "Cheating, plagiarism, or copying another participant's work results in immediate disqualification.",
      "The jury's decision is final.",
    ],
    whatYouNeed: [
      "Mime attire: black pants, black T-shirt, white gloves or painted hands, white face paint.",
      "Audio file in MP3 format (max 10 MB), submitted 60 minutes before the event.",
    ],
    important: ["No props allowed during the performance."],
    evaluationCriteria: ["Body language and expression", "Concept and storytelling", "Rhythm, timing and coordination", "Character personation", "Relevance to theme"],
  },
  {
    slug: "imaginarium",
    name: "Imaginarium",
    category: "literary",
    format: "Individual",
    participantsLabel: "1 participant",
    participantsCount: 1,
    theme: "On spot (a single image shown at the start)",
    timeLimit: "60 minutes",
    about: "An on-the-spot creative writing event where participants respond to a single displayed image with an original piece of writing.",
    requirements: ["1 participant per campus."],
    rules: [
      "Registration begins 60 minutes before the event.",
      "Participants must report 15 minutes before the event begins.",
      "Performance time limit is 60 minutes.",
      "A single image is displayed to all participants at the start.",
      "Participants may choose from: short story, poem, monologue, memoir, or scene from a novel.",
      "The write-up must have a heading relevant to the content.",
      "Writing must be original and created during the competition.",
      "Word limit: 300 words (does not apply to poetry).",
      "The write-up may be presented in English or Hindi.",
      "Mobile phones, internet access, AI tools, books, and reference materials are not permitted.",
      "Plagiarism or copying results in disqualification.",
      "The jury's decision is final.",
    ],
    important: ["Mobile phones, internet access, AI tools, books, and reference materials are not permitted."],
    evaluationCriteria: ["Writing quality (imagery, metaphor, narrative)", "Grammar and coherence", "Conceptual depth", "Creativity and interpretation", "Overall impact"],
  },
  {
    slug: "ad-mad",
    name: "Ad-Mad",
    category: "literary",
    format: "Group",
    participantsLabel: "3 participants",
    participantsCount: 3,
    theme: "Provided at the time of registration",
    timeLimit: "30 minutes ideation + 3 minutes performance",
    about: "A live advertisement-creation event where teams promote and sell a given product to the jury through a jingle, act, or song.",
    requirements: ["3 participants per campus."],
    rules: [
      "Registration begins 60 minutes before the event.",
      "Time limit for ideation and prop preparation is 30 minutes.",
      "Performance duration is 3 minutes.",
      "The advertisement may be presented in English or Hindi.",
      "Participants must carry the required stationery and materials (A4 sheets, coloured paper, scissors, DST, etc.).",
      "The advertisement should be presented as a jingle, act, or song promoting the given product.",
      "Plagiarism or offensive language results in disqualification.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["Own stationery and prop materials (A4 sheets, coloured paper, scissors, DST, etc.)."],
    evaluationCriteria: ["Presentation and engagement", "Team work and acting", "Overall impact", "Clarity of message"],
  },
  {
    slug: "meme-making",
    name: "Meme Making",
    category: "literary",
    format: "Individual",
    participantsLabel: "1 participant",
    participantsCount: 1,
    theme: "On the spot (announced at registration)",
    timeLimit: "Submission-based — within 24 hours of registration",
    about: "A submission-based digital meme-making event on an on-the-spot theme.",
    requirements: ["1 participant per campus."],
    rules: [
      "Registration begins 24 hours before the event; the theme is provided at registration.",
      "The meme must be submitted within 24 hours of registration, in digital, portrait-layout format.",
      "File must be JPEG format, maximum size 5 MB.",
      "Entries are submitted at the provided drive link using the participant's NIFT email ID.",
      "Late entries are not accepted; non-submission within 24 hours results in cancellation of participation.",
      "Plagiarism or offensive content results in disqualification.",
      "The jury's decision is final.",
    ],
    whatYouNeed: ["Digital meme file: JPEG format, portrait layout, max 5 MB."],
    evaluationCriteria: ["Adherence to theme", "Humour and wit", "Visual appeal and composition", "Message clarity", "Creativity/originality"],
  },
  {
    slug: "big-bait",
    name: "Big Bait",
    category: "literary",
    format: "Group",
    participantsLabel: "2 participants",
    participantsCount: 2,
    theme: "Chosen by the team from 12 given topics (Fashion & Lifestyle, Retail & Consumer Innovation, Sustainability & Circularity, Craft & Cultural Heritage, Social Innovation, Creative Entrepreneurship, Future of Fashion & New-Age Experiences, Inclusive Fashion & Design, Fashion Wellness & Lifestyle, AI/Digital & Smart Fashion, Immersive & Virtual Experiences, Digital Creator Economy & Content Innovation)",
    timeLimit: "Round 1: 1-minute pitch. Round 2: 15 minutes (10 min presentation + 5 min Q&A)",
    about: "A two-round startup-style pitch competition. Teams choose one of twelve given topics and pitch an idea to a panel of evaluators.",
    requirements: ["2 participants per campus."],
    rules: [
      "Registration begins 1 hour before the event; 5 minutes provided for presentation set-up.",
      "Each team selects one of the 12 given topics.",
      "Round 1 — Evaluator Pitch: 1 minute per team, covering the problem/opportunity, innovation, value proposition, potential, and overall pitching. Top 6 teams advance.",
      "Round 2 — Final Presentation: 15 minutes total (10 minutes presentation + 5 minutes questions from the jury), for the 6 finalist teams.",
      "Each team may bring a prototype, poster, product, or other supporting material for the final presentation.",
      "The jury's decision is final at both rounds.",
    ],
    whatYouNeed: ["Optional prototype, poster or product to support Round 2 presentation."],
    evaluationCriteria: ["Problem/opportunity & market understanding", "Innovation and unique value proposition", "Feasibility and business implementation model", "Impact and scalability", "Pitch presentation & Q&A"],
  },

  // ---------------- ADVENTURE & PHOTOGRAPHY ----------------
  {
    slug: "short-film",
    name: "Short Film",
    category: "photography",
    format: "Solo/Duet",
    participantsLabel: "1 or 2 participants",
    theme: "Announced at registration",
    timeLimit: "3–4 minutes runtime",
    about: "A themed short film shot entirely during the officially designated Converge shooting window, submitted anonymously by participant code.",
    requirements: ["1 or 2 participants per campus."],
    rules: [
      "The theme is announced only at registration; a unique participant code is issued for anonymous submission.",
      "The submission must present a complete narrative (script/description) and a coherent visual concept.",
      "The film must be 3–4 minutes long.",
      "The entire film must be shot during the officially designated Converge 2026 shooting window announced at registration; stock or previously recorded footage is prohibited.",
      "Filming is permitted only at officially designated Converge venues announced at registration.",
      "Mobile phones, DSLRs, mirrorless cameras, action cameras, or camcorders may be used.",
      "Trimming, sequencing, colour correction, brightness/contrast adjustment, audio balancing, and subtitles are permitted. AI-generated visuals/voices, AI-assisted object insertion/removal, deepfakes, and other authenticity-altering manipulation are prohibited.",
      "All footage, music, and sound effects must be original or royalty-free; participants are responsible for any copyright infringement.",
      "Dangerous acts, damage to property, or violations of institute rules may result in immediate disqualification.",
      "Submit as MP4 or MOV, minimum Full HD (1920×1080); maximum file size announced at registration.",
      "A 50–100 word synopsis must accompany the submission.",
      "The film and synopsis must not contain the participant's name, institute name, logo, watermark, credits, or other identifying information — violations lead to disqualification.",
      "Submissions are emailed to the host campus's photography club by the announced deadline, in the format: Short Film - Theme - Participant Code.",
      "Late, ineligible, incomplete, or corrupt entries may be disqualified at any stage.",
      "The jury's decision is final and binding.",
    ],
    whatYouNeed: ["A recording device (mobile phone, DSLR, mirrorless, action camera, or camcorder)."],
    important: ["Submission must not contain any identifying information — anonymised by participant code only."],
    evaluationCriteria: ["Concept & storytelling", "Creativity & originality", "Visual composition & cinematography", "Technical quality (sound, editing & lighting)", "Overall impact & theme interpretation"],
  },
  {
    slug: "concept-photography",
    name: "Concept Photography",
    category: "photography",
    format: "Individual",
    participantsLabel: "1 participant",
    participantsCount: 1,
    theme: "Announced at registration",
    about: "A themed single-photograph submission, shot entirely during the officially designated Converge shooting window and submitted anonymously by participant code.",
    requirements: ["1 participant per campus."],
    rules: [
      "The theme is announced only at registration; a unique participant code is issued for anonymous submission.",
      "Photography using any type of camera, including mobile cameras, is permitted.",
      "The photograph must be captured during the officially designated Converge 2026 shooting window announced at registration; previously captured or stock photographs are prohibited.",
      "Photography is permitted only at officially designated Converge venues announced at registration.",
      "Cropping, colour correction, exposure/brightness/contrast adjustment, and sharpening are permitted. AI-generated imagery, generative fill, compositing, AI-assisted object insertion/removal, and other authenticity-altering manipulation are prohibited.",
      "A title and a 50–100-word description explaining the concept must accompany the photograph.",
      "Submit as JPEG/JPG or PNG; minimum pixel dimensions and maximum file size announced at registration.",
      "The photograph and description must not contain the participant's name, institute name, logo, watermark, credits, or other identifying information — violations lead to disqualification.",
      "The photograph must be original work; participants are responsible for obtaining permissions for identifiable persons, private property, or protected content shown.",
      "Dangerous acts, damage to property, or violations of institute rules may result in immediate disqualification.",
      "Submissions are emailed to the host campus's photography club by the announced deadline, in the format: Concept Photography - Theme - Participant Code.",
      "Late, ineligible, incomplete, or corrupt entries may be disqualified at any stage.",
      "The jury's decision is final and binding.",
    ],
    whatYouNeed: ["A camera (any type, including mobile)."],
    important: ["Submission must not contain any identifying information — anonymised by participant code only."],
    evaluationCriteria: ["Concept & theme interpretation", "Visual composition", "Creativity & originality", "Technical quality", "Overall impact"],
  },
  {
    slug: "reel-making",
    name: "Reel Making",
    category: "photography",
    format: "Individual",
    participantsLabel: "1 participant",
    participantsCount: 1,
    theme: "Announced at registration",
    about: "A themed short-form video reel shot entirely during the officially designated Converge shooting window, submitted anonymously by participant code.",
    requirements: ["1 participant per campus."],
    rules: [
      "The theme is announced only at registration; a unique participant code is issued for anonymous submission.",
      "The reel must present a coherent visual concept or story clearly related to the theme.",
      "The permitted reel duration is announced at registration.",
      "The entire reel must be shot during the officially designated Converge 2026 shooting window announced at registration; stock or previously recorded footage is prohibited.",
      "Filming is permitted only at officially designated Converge venues announced at registration.",
      "Mobile phones, DSLRs, mirrorless cameras, action cameras, or camcorders may be used.",
      "Trimming, sequencing, transitions, colour correction, brightness/contrast adjustment, audio balancing, and subtitles are permitted. AI-generated visuals/voices, generative fill, AI-assisted object insertion/removal, deepfakes, and other authenticity-altering manipulation are prohibited.",
      "All footage, music, and sound effects must be original or royalty-free; participants are responsible for any copyright infringement.",
      "Dangerous acts, damage to property, or violations of institute rules may result in immediate disqualification.",
      "A title and a 50–100 word description explaining the concept must accompany the reel.",
      "Submit as MP4 or MOV, minimum 1080p; required aspect ratio and maximum file size announced at registration.",
      "The reel and description must not contain the participant's name, institute name, logo, watermark, credits, or other identifying information — violations lead to disqualification.",
      "Submissions are emailed to the host campus's photography club by the announced deadline, in the format: Reel Making - Theme - Participant Code.",
      "Late, ineligible, incomplete, or corrupt entries may be disqualified at any stage.",
      "The jury's decision is final and binding.",
    ],
    whatYouNeed: ["A recording device (mobile phone, DSLR, mirrorless, action camera, or camcorder)."],
    important: ["Submission must not contain any identifying information — anonymised by participant code only."],
    evaluationCriteria: ["Theme interpretation & concept", "Creativity & originality", "Visual composition & storytelling", "Editing, sound & technical quality", "Overall impact & engagement"],
  },
];

export function getEventsByCategory(category: string) {
  return EVENTS.filter((e) => e.category === category);
}

export function getEventBySlug(category: string, slug: string) {
  return EVENTS.find((e) => e.category === category && e.slug === slug);
}
